### ISSUE TITLE
Länken till https://github.com/jacobk/ratingkartan/issues är ej klickbar på info-sidan.

### ISSUE THREAD

**Issue by Li1633Ca** [jacobk/ratingkartan#27]
Även om länken till https://github.com/jacobk/ratingkartan/issues ser ut att vara en klickbar länk på https://jacobk.github.io/ratingkartan/#/info är den inte det. 
Lägga till href="https://github.com/jacobk/ratingkartan/issues" i a-taggen?

**Comment by jacobk** [comment]
Tack för att du rapportera! Fixat nu ;)
