### ISSUE TITLE
Oförändrad rating visas som föregående månads förändring.

### ISSUE THREAD

**Issue by Peiza** [jacobk/ratingkartan#33]
Upptäckte att om ens rating hamnar på samma poäng som föregående månad visas den månadens förändring fortfarande. Som i mitt fall att jag gick +7 i månades uppdatering, men i själva verket var det +- 0. 

Samma sak gäller personer som inte har några nya resultat under månaden, men där är det samma sak hos PDGA, att man står kvar med förändringen som var senast. Dock står det föregående månads datum inom parantes där, så det blir tydligt. 

Som exempel kan du kika på #188063 och #145501

**Comment by jacobk** [comment]
Fixat import scriptet nu, kolla gärna om det fortfarande ser fel ut.
